config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "posts#index"

  resources :users
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255 }, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: "投稿に成功しました！"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "投稿を更新しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :description, :image, :price)
    end

    def find_post
      @post = Post.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'メールアドレスとパスワードの組合わせが間違っています'
      redirect_back_or user
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user, notice: "ユーザー登録に成功しました！"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "ユーザー情報を更新しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def find_user
      @user = User.find(params[:id])
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください！"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end


  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ikittokei~時計の転売サイト~</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to "IKITTOKEI ~時計の転売サイト", root_path%>
          <% if logged_in?%>
          <ul class="navbar-nav navbar-right">
            <li class="nav-item" style="list-style:none;">
              <a class="nav-link"><%= link_to "新規投稿", new_post_path %></a>
            </li>
            <li class="nav-item" style="list-style:none;">
              <a class="nav-link"><%= link_to "ユーザー一覧", users_path %></a>
            </li>
            <li class="nav-item" style="list-style:none;">
              <a class="nav-link"><%= link_to "ログアウト", logout_path, method: :delete %></a>
            </li>

              <li class="nav-item" style="list-style:none;color:#A52A2A;">
                <strong><p>@<%= current_user.name %></p></strong>

            </li>


          </ul>


          <% else %>
          <ul class="navbar-nav navbar-right">
            <li class="nav-item" style="list-style:none;">
              <a class="nav-link"><%= link_to "新規登録", signup_path %></a>
            </li>
            <li class="nav-item" style="list-style:none;">
              <a class="nav-link"><%= link_to "ログイン", login_path %></li></a>
            </li>
          </ul>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-info"%>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error" )%>
      prevented this Post from saving
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <strong>※価格は架空の通貨単位はbonzoです。</strong>
</p>
<p style="color:red;">  ※サンプルサイトであり、このサイトで生じた不利益について管理者は一切の責任を負いません。
</p>

<div class="form-group">
  <%= f.input :image, input_html: { class: 'form-control' }%>
</div>
<div class="form-group">
  <%= f.input :title, input_html: { class: 'form-control' }%>
</div>
<div class="form-group">
  <%= f.input :price, input_html: { class: 'form-control' }%>
</div>
<div class="form-group">
  <%= f.input :description, input_html: { class: 'form-control' }%>
</div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <h1>編集</h1>
  <%= image_tag @post.image.url(:medium)%>
  <%= render 'form'%>

  <%= link_to "キャンセル", post_path%>

</div>

app/views/posts/index.html.erb
<div id="posts" class="transitions-enabled">
    <%@posts.each do |post| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag post.image.url) , post%>
      <div class="panel-body">
        <h2><%= link_to post.title, post %></h2>
      </div>
    </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>新規投稿</h1>

  <%= render 'form' %>
  <%= link_to "戻る", root_path %>

</div>

app/views/posts/show.html.erb
<div id="post_show" class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading post_image">
        <%= image_tag @post.image.url(:medium)%>
      </div>
        <div class="panel-body">
          <h1><%= @post.title %></h1>
          <h2>
            <strong>価格(bonzo):</strong>
            <%= @post.price %>
          </h2>
          <p>
            <strong>※価格は架空の通貨単位:bonzoです。</strong>
          </p>
          <p style="color:red;">  ※サンプルサイトであり、このサイトで生じた不利益について管理者は一切の責任を負いません。
          </p>
          <p> <%= @post.description %></p>
          <p> <%= @post.user.email %></p>
        </div>

        <% if logged_in?%>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-6 btn-group pull-right">
                <%= link_to "購入",'#', class: "btn btn-primary"%>
                <% if @post.user_id == @current_user.id%>
              </div>
            </div>
            </div>
                <div class="panel-footer">
                  <div class="row">
                    <div class="col-md-6 btn-group pull-right">
                      <%= link_to "戻る", root_path , class:"btn btn-default"%>
                      <%= link_to "編集", edit_post_path , class: "btn btn-default"%>
                      <%= link_to "削除", post_path, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-default"%>
                    </div>
                  </div>
                </div>

                <% end %>
        <% end %>


      </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for @user, html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@user.errors.count, "error" )%>
      prevented this Post from saving
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= f.input :name, input_html: { class: 'form-control' }%>
</div>
<div class="form-group">
  <%= f.input :email, input_html: { class: 'form-control' }%>
</div>
<div class="form-group">
  <%= f.input :password, input_html: { class: 'form-control' }%>
</div>
<div class="form-group">
  <%= f.input :password_confirmation, input_html: { class: 'form-control' }%>
</div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <h1>ユーザー編集</h1>
  <%= render 'form'%>

  <%= link_to "キャンセル", user_path, class: "btn btn-default"%>
  <%= link_to "削除", user_path, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-default"%>

</div>

app/views/users/index.html.erb
<div id="users">
    <%@users.each do |user| %>
    <div class="box panel panel-default">
      <div class="panel-body">
        <h2><%= link_to user.name, user %></h2>
      </div>
    </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>ユーザー登録</h1>

  <%= render 'form' %>
  <%= link_to "戻る", root_path %>

</div>

app/views/users/show.html.erb
<div id="usert_show" class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
        <div class="panel-body">
          <h1><%= @user.name %></h1>
          <p> <%= @user.email %></p>
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-6 btn-group pull-right">
                <%= link_to "戻る", root_path , class:"btn btn-default"%>
                <%= link_to "編集", edit_user_path , class: "btn btn-default"%>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>